<h2>Users</h2>

<div>
    <form method="post" action="user/login">
        <input type="text" id="login" name="login" placeholder="login">
        <input type="password" id="password" name="password" placeholder="password">
        <button type="submit">Login</button>
    </form>
</div>

<?php if (property_exists($single, 'id')):?>
    <?=$single->id?>
    <?=$single->email?>
    <h5>Projects</h5>
    <?php foreach ($single->project as $project): ?>
        <p>
            <?=$project->id?>
            <?=$project->title?>
        </p>
    <?php endforeach;?>

<br/>
<?php endif;?>
<hr>
<?php foreach ($all as $user): ?>
    <?=$user->id?>
    <?=$user->email?>
<br/>
<?php endforeach;?>
